/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TournamentsNewRouteImport } from './routes/tournaments/new'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments/$tournamentId'
import { Route as PlayersUserIdRouteImport } from './routes/players/$userId'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as TournamentsTournamentIdMatchMatchIdRouteImport } from './routes/tournaments/$tournamentId/match/$matchId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsNewRoute = TournamentsNewRouteImport.update({
  id: '/tournaments/new',
  path: '/tournaments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/tournaments/$tournamentId',
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersUserIdRoute = PlayersUserIdRouteImport.update({
  id: '/players/$userId',
  path: '/players/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)
const TournamentsTournamentIdMatchMatchIdRoute =
  TournamentsTournamentIdMatchMatchIdRouteImport.update({
    id: '/match/$matchId',
    path: '/match/$matchId',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteWithChildren
  '/tournaments/new': typeof TournamentsNewRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/match/$matchId': typeof TournamentsTournamentIdMatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/match/$matchId': typeof TournamentsTournamentIdMatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteWithChildren
  '/tournaments/new': typeof TournamentsNewRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/match/$matchId': typeof TournamentsTournamentIdMatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/players/$userId'
    | '/tournaments/$tournamentId'
    | '/tournaments/new'
    | '/tournaments/'
    | '/tournaments/$tournamentId/'
    | '/tournaments/$tournamentId/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/players/$userId'
    | '/tournaments/new'
    | '/tournaments'
    | '/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/players/$userId'
    | '/tournaments/$tournamentId'
    | '/tournaments/new'
    | '/tournaments/'
    | '/tournaments/$tournamentId/'
    | '/tournaments/$tournamentId/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PlayersUserIdRoute: typeof PlayersUserIdRoute
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRouteWithChildren
  TournamentsNewRoute: typeof TournamentsNewRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/new': {
      id: '/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof TournamentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$userId': {
      id: '/players/$userId'
      path: '/players/$userId'
      fullPath: '/players/$userId'
      preLoaderRoute: typeof PlayersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/'
      fullPath: '/tournaments/$tournamentId/'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof TournamentsTournamentIdRoute
    }
    '/tournaments/$tournamentId/match/$matchId': {
      id: '/tournaments/$tournamentId/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/tournaments/$tournamentId/match/$matchId'
      preLoaderRoute: typeof TournamentsTournamentIdMatchMatchIdRouteImport
      parentRoute: typeof TournamentsTournamentIdRoute
    }
  }
}

interface TournamentsTournamentIdRouteChildren {
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
  TournamentsTournamentIdMatchMatchIdRoute: typeof TournamentsTournamentIdMatchMatchIdRoute
}

const TournamentsTournamentIdRouteChildren: TournamentsTournamentIdRouteChildren =
  {
    TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
    TournamentsTournamentIdMatchMatchIdRoute:
      TournamentsTournamentIdMatchMatchIdRoute,
  }

const TournamentsTournamentIdRouteWithChildren =
  TournamentsTournamentIdRoute._addFileChildren(
    TournamentsTournamentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PlayersUserIdRoute: PlayersUserIdRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRouteWithChildren,
  TournamentsNewRoute: TournamentsNewRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
